etn-ccis/blui-react-native-themes

README.md

- link to npm from badge
- 
- 
-

link out to npm

---

README.md
package.json
src/blueDarkTheme.ts
src/blueTheme.ts
src/index.ts
src/shared.ts

Fixes PXBLUE-2421.
- Update theme structure

Update theme structure

---

CHANGELOG.md
package.json

Merges dev into release/6.0.0 to prep for publishing

Prepare for publishing

---

CHANGELOG.md

Update release date in CHANGELOG.md for v5.2.0 release

[1] Update release date in CHANGELOG.md

---

.circleci/config.yml
CHANGELOG.md
README.md
package.json
src/blueDarkAltTheme.ts
src/index.ts

Publishes v5.2.0
** wait for changelog update with proper release date (https://github.com/pxblue/react-native-themes/pull/14)

[2] Publish v5.2.0

---

README.md

R21 cleanup

---

CHANGELOG.md
package.json

Fixes # PXBLUE-2506
- Update changelog and package

PXBLUE-2506 Updated changelog

---

.circleci/config.yml
CHANGELOG.md
README.md
package.json
scripts/linkThemes.sh
src/blueDarkAltTheme.ts
src/blueDarkTheme.ts
src/blueTheme.ts
yarn.lock

Fixes PXBLUE-2684.
- Remove PX Blue references

Blui-fy Themes repo version n-1

---

package.json
scripts/buildTest.sh
yarn.lock

Fixes # .
- update to include licenses.json in dist bundle
- add precommit
- update test for licenses file
- open branch
- remove licenses json file
- run precommit

add precommit and license test

---

.gitmodules
CODEOWNERS
LICENSES.json
README.md
package.json

- Updated links to their GHE equivalences
- Updated code owners

Update GHE links and code owners

---

src/blueDarkTheme.ts
src/blueTheme.ts

Fixes # .
- Custom colors fixes
- Added 2 more custom colors in the themes
-
-
-

Custom colors fix and add 2 colors 

---

src/blueDarkTheme.ts
src/blueTheme.ts
src/shared.ts

- add surfaceDisable and onSurfaceDisabled for both themes. Used for buttons and other RNP components
-
-
-
-
-

Add surfaceDisabled & onSurfaceDisabled

---

LICENSES.json
package.json
src/blueDarkTheme.ts
src/blueTheme.ts
src/index.ts
src/shared.ts
yarn.lock

- Move extendedAppTheme() in react native
- Update colors package
- Publish alpha version
-
-
-

Add extendedAppTheme hook in themes

---

src/blueDarkTheme.ts
src/blueTheme.ts
src/shared.ts

Fixes #BLUI-5000 .
- Added sliderTrack and sliderTrackDisabled color variants in both light and dark themes.
- Added type augmentation for newly added color variants.
-
- yarn start
-

[React Native Themes] #62 Add colors for custom slider track

---

src/blueDarkTheme.ts
src/blueTheme.ts
src/shared.ts

Fixes 4987 .
- Add status color for blue and blueDark
- Adding Comments to colors is remaining 
-
-
-
-

add status colors with containers

---

package.json

Fixes # .
- Updated the alpha package version
-
-
-

Publishing 7.0.0-alpha.2 package

---

README.md

Fixes # BLUi-4359
- Added migration guide to readme
- 
-
-

Updated migration guide to readme

---

package.json
src/blueDarkTheme.ts
src/blueTheme.ts

Fixes #BLUI-4954 .
- Added backdrop color variant
-
-

Publish React native themes

---

src/blueDarkTheme.ts
src/blueTheme.ts

add comments for elevation
-
-
-
-
-
-

Add comments for elevation level

---

package.json

Fixes # .
- Publish alpha package for fonts test.
-
-
-
-
-

Publish alpha package for fonts test 

---

package.json

Revert unpublished package

---

.github/workflows/blui-ci.yml
package.json

publish failed package

---

.github/workflows/blui-ci.yml
package.json

Fixes # .
- test publish with npm run publish:package
-
-
-
-
-

test npm publish & revert alpha

---

package.json

Fixes # .
- test publish alpha dev branch 
-
-
-
-
-

tests publish alpha

---

.github/workflows/blui-ci.yml
package.json

test with new token

---

.github/workflows/blui-ci.yml

use npm run publish

---

package.json
src/shared.ts

font families are case sensitive

---

README.md

update readme code for useFontWeight

---

package.json

Fixes #5589
- React native Themes Version update
-
-
-

React native Themes Version update

---

CHANGELOG.md

Fixes # .
- Release Date Update
-
-
-

Release Date Update
